spring:
  application:
    name: oddjobs-backend
  datasource:
    url: ${ODDJOBS_DB_URL:jdbc:postgresql://localhost:9993/helloworld}
    username: ${ODDJOBS_DB_USER:helloworld}
    password: ${ODDJOBS_DB_PASSWORD:helloworld}
  flyway:
    enabled: true
    locations: classpath:db/migration
  jooq:
    sql-dialect: postgres

  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
server:
  port: 8080
